Capitulo 3 HTML5
Juan-Alejandro-Arriaga/html5 pull request #10
Opened 2024-10-08 20:55 UTC by Juan-Alejandro-Arriaga

# what
* Capitulo 3 del curso de HTML5
# why
* Continuación con la capacitación de HTML5
* Be concise and to the point 
# references
* https://diveinto.html5doctor.com/semantics.html

2024-10-08 23:32 UTC, semanticmx requested changes
muy bien!, unos cambios más y queda

2024-10-08 23:32 UTC, semanticmx commented on cap-03/README.md
> +* **Modo peculiaridades**
estos déjalos en su versión en inglés

2024-10-08 23:32 UTC, semanticmx commented on cap-03/README.md
> +* *Meta*
las etiquetas van en minúsculas

2024-10-08 23:32 UTC, semanticmx commented on cap-03/README.md
> +## Other link relations in HTML5
No todos los títulos tienen que quedar en inglés :)

2024-10-08 23:32 UTC, semanticmx commented on cap-03/README.md
> +    <p class="post-date">October 22, 2009</p>
aquí faltó identar el código

2024-10-08 23:32 UTC, semanticmx commented on cap-03/README.md
> +        <a href="#"
muy bien, este es el formato que necesitamos para los atributos

2024-10-08 23:32 UTC, semanticmx commented on cap-03/README.md
> +       <div id="w3c_footer">
acá sobraron espacios en la identación

2024-10-09 19:24 UTC, Carmen-Mercado requested changes

2024-10-09 19:24 UTC, Carmen-Mercado commented on cap-03/README.md
> +    <div id="w3c_footer">
puedes cambiar el div por una etiqueta footer y trata de seguir  las guías de buenas practicas para html, te dejo por acá dos links de guías que te pueden ayudar.
[HTML Coding Guidelines](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Guidelines/Code_guidelines/HTML).
[Google HTML/CSS Style Guide](https://google.github.io/styleguide/htmlcssguide.html)​

2024-10-10 15:41 UTC, semanticmx requested changes

2024-10-10 15:41 UTC, semanticmx commented on cap-01/README.md
> +# ¿Como llegamos hasta aquí?
@Carmen-Mercado podrías checar con Alex este tema?

Creo que está haciendo el PR medio raro porque el cap-01 no debería estar en el PR del Cap 3 y menos el archivos que se agrege completo

2024-10-15 18:29 UTC, semanticmx requested changes

2024-10-15 18:29 UTC, semanticmx commented on cap-03/src/index.html
> +                    <li><a href="#">home</a></li>
@Juan-Alejandro-Arriaga podrías actualizar el repo de estándares de código con un PR para agregar la siguiente documentación?

El formato de HTML debe ser una etiqueta por línea con etiquetas anidadas usando identación.

Para los atributos cuando sea el caso de que se tenga más de uno cada uno se escribirá en su propia línea.

Ejemplos:

**OK**

```
<title>Mi pagina web</title>
```

**Mejor**

```
<title>
  Mi pagina web
</title>
```

**Incorrecto**

```
<li><a href="#">home</a></li>
```

**Mejor**

```
<li>
  <a href="#">
    home
  </a>
</li>
```

**Incorrecto**

```
<link rel="stylesheet" href="style.css" type="text/css">
```

**Mejor**

```
<link 
  rel="stylesheet" 
  href="style.css" 
  type="text/css">
```

2024-10-15 18:29 UTC, semanticmx commented on cap-03/src/index.html
> +                <td><a href="https://diveinto.html5doctor.com/semantics.html">Vos vestros servate, meos mihi linquite mores</a></td>
y hay que aplicar esas correcciones a todo el código por favor

2024-10-15 19:33 UTC, semanticmx commented on cap-03/src/index.html
> +            <a
cuando es el caso de un solo atributo, ese si puede ir en la misma línea.

2024-10-15 19:33 UTC, semanticmx approved these changes
gracias!

2024-10-17 03:13 UTC, Carmen-Mercado approved these changes
Muy bien, gracias!

2024-10-17 03:13 UTC, Carmen-Mercado commented on cap-01/README.md
> +1. Deben ser compatibles con versiones anteriores
Si vas a usar este tipo de listas ten cuidado con los índices.

2024-10-17 03:13 UTC, Carmen-Mercado commented on cap-03/src/index.html
> +<!DOCTYPE html>
Trata de dar formato al código utilizando buenas practicas, trata de seguir los consejos que dan en los links que te proporcione en la última revision, por favor

2024-10-17 03:13 UTC, Carmen-Mercado commented on cap-03/src/index.html
> +</html>
Acá falta agregar un enter al final del archivo

2024-10-17 03:13 UTC, Carmen-Mercado commented on cap-01/README.md
> +# ¿Como llegamos hasta aquí?
Hola, claro, lo reviso!

2024-10-21 15:52 UTC, merged