Capitulo 4 HTML5 Resumen
Juan-Alejandro-Arriaga/html5 pull request #11
Opened 2024-10-15 18:01 UTC by Juan-Alejandro-Arriaga

# what
* Resumen del curso de HTML5 del capitulo 4
# why
* Continuación de mis capacitaciones de HTML5
project root.)

# references
* https://diveinto.html5doctor.com/canvas.html

2024-10-17 04:57 UTC, semanticmx commented on cap-04/README.md
> +      <!--[if lt IE 9]>
aquí la identación está medio rara

2024-10-17 04:58 UTC, semanticmx commented on cap-04/src/index.html
> +        *{
No es parte del HTML pero hay que dejar un espacio entre los elementos y la llave de los estilos:

en lugar de:

```
canvas{
```

debe ser:

```
canvas {
```

2024-10-17 05:01 UTC, semanticmx requested changes
unos ajustes de estilo y queda

2024-10-17 05:01 UTC, semanticmx commented on cap-04/src/index.html
> +        <div
vamos a hacer un ajuste y dejar el `>` en una nueva línea también

en lugar de:

```html
<canvas 
                    id="canva_identificado"
                    onclick="dibujaforma()">
```

que sea:

```html
<canvas 
                    id="canva_identificado"
                    onclick="dibujaforma()"
>
```

Lo puedes agregar en otro PR al repo de estándares?

2024-10-17 05:01 UTC, semanticmx commented on cap-04/src/index.html
> +        <p>
Esta `p` y las de abajo están mal identadas

2024-10-17 05:01 UTC, semanticmx commented on cap-04/src/index.html
> +        </div>
y eso hace que este `</div>` no se vea a que etiqueta de apertura pertenece

2024-10-17 05:01 UTC, semanticmx commented on cap-04/src/index.html
> +        <div
Acá se ve mejor la identación

2024-10-21 17:22 UTC, Carmen-Mercado requested changes

2024-10-21 17:22 UTC, Carmen-Mercado commented on cap-04/README.md
> +`<canvas height="300" width="255"></canvas>`
cuando tengas este caso puedes usar la siguiente estructura 
`<canvas
    height="300"
    width="255"
 />

2024-10-21 17:22 UTC, Carmen-Mercado commented on cap-04/README.md
> +    <img id="cat" src="images/cat.png" alt="sleeping cat" width="177" height="113">
No olvides la identación

2024-10-21 17:22 UTC, Carmen-Mercado commented on cap-04/README.md
> +    <img
No olvides cerrar las etiquetas

2024-10-21 17:22 UTC, Carmen-Mercado commented on cap-04/src/index.html
> +                >
Cuando tengas estos casos puedes usar etiquetas de cierre 
<canvas
   id="canva"
/>

2024-10-21 17:22 UTC, Carmen-Mercado commented on cap-04/src/index.html
> +        <script>
No necesitas agregar varios scripts puedes colocar todas las funciones en uno solo

2024-10-21 21:01 UTC, semanticmx commented on cap-04/README.md
> +    >
se ve bien, solo hay que corregir lo de la etiqueta vacía y queda.

2024-11-12 17:15 UTC, Carmen-Mercado approved these changes

2024-11-12 17:15 UTC, Carmen-Mercado commented on cap-04/README.md
> +    <canvas
En estos casos puedes cerrar en linea la etiqueta, es decir sin etiqueta de cierre <canvas />

2024-11-19 17:33 UTC, semanticmx commented on cap-04/README.md
> +    <canvas
`canva` si ocupa etiqueta de apertura y cierre

2024-11-19 17:34 UTC, semanticmx approved these changes
muy bien!

2024-11-19 19:15 UTC, merged