|Cap 5 html5
Juan-Alejandro-Arriaga/html5 pull request #13
Opened 2024-10-29 15:26 UTC by Juan-Alejandro-Arriaga

# what
* Capitulo 5 del curso de HTML5
# why
* Continuación con capacitación en HTML5
# references
* https://diveinto.html5doctor.com/video.html

2024-10-29 21:58 UTC, semanticmx requested changes

2024-10-29 21:58 UTC, semanticmx commented on cap-05/README.md
> +<table>
faltó el formato de código con los tres acentos inversos.

2024-10-29 21:58 UTC, semanticmx commented on cap-05/README.md
> +```html
muy bien!

2024-10-29 21:58 UTC, semanticmx commented on cap-05/src/index.html
> +</html>
muy bien!

2024-10-29 22:09 UTC, semanticmx approved these changes

2024-10-30 21:59 UTC, Carmen-Mercado approved these changes

2024-10-30 21:59 UTC, Carmen-Mercado commented on cap-05/src/index.html
> +                class=""
Acá te falto la clase

2024-10-30 23:39 UTC, semanticmx approved these changes

2024-10-30 23:39 UTC, semanticmx commented on cap-05/README.md
> +Los archivos de vid0oeo como *"AVI"* o *"MP4"* son formatos de contenedores que definen como almace-nar cosas dentro de ellos.
dice `vid0oeo`

2024-11-04 21:59 UTC, merged