Capitulo 7 libro HTML5
Juan-Alejandro-Arriaga/html5 pull request #15
Opened 2024-11-06 23:44 UTC by Juan-Alejandro-Arriaga

# what
* Capitulo 7 del libro de HTML5
# why
* Continuación con los cursos de HTML5
# references
* https://diveinto.html5doctor.com/storage.html

2024-11-07 14:06 UTC, semanticmx commented on cap-07/README.md
> +```JS
de preferencia hay que usar `javascript` en lugar de `JS`

2024-11-07 14:07 UTC, semanticmx commented on cap-07/README.md
> +    <button
la alineación está un poco rara, la etiqueta `button` de apertura y cierre debe coincidir en la misma columna.

2024-11-07 14:07 UTC, semanticmx commented on cap-07/src/index.html
> +                const ram =parseInt(Math.random() * 6);
creo que esta variable debería ser `ran`

2024-11-07 14:08 UTC, semanticmx approved these changes
muy bien!

2024-11-07 20:17 UTC, Carmen-Mercado requested changes
De igual forma si puedes incluir el cambio de JS a javascript como lo menciono el ingeniero estaría genial, gracias!

2024-11-07 20:17 UTC, Carmen-Mercado commented on cap-07/README.md
> +Con JS accederás al "*HTML5 Storage*" con el objeto de "*localStrogare*" aun así se debe detectar si el navegador lo soporta.
Esta mal escrito es "localStorage"

2024-11-07 20:17 UTC, Carmen-Mercado commented on cap-07/README.md
> +    var foo = localStorage.getItem("bar");
Cuida mayusculas y minúsculas

2024-11-12 17:06 UTC, Carmen-Mercado approved these changes
Perfecto, muchas gracias!

2024-11-12 17:16 UTC, merged