Cap 9 Curos Html5
Juan-Alejandro-Arriaga/html5 pull request #17
Opened 2024-11-19 19:15 UTC by Juan-Alejandro-Arriaga

# what
* Resumen del capitulo 9 de cursos de HTML5
# why
* Continuación de cursos de HTML5
# references
* https://diveinto.html5doctor.com/forms.html

2024-11-20 17:21 UTC, semanticmx requested changes
gracias!

2024-11-20 17:21 UTC, semanticmx commented on cap-09/README.md
> +        <script src=jquery.min.js></script>
src tiene que ir entre comillas:

`<script src="jquery.min.js"></script>`

2024-11-20 17:21 UTC, semanticmx commented on cap-09/README.md
> +          <input id="q" autofocus>
estos también se consideran atributos así que va uno por línea

2024-11-20 17:21 UTC, semanticmx commented on cap-09/README.md
> +    <input
muy bien, como punto extra los puedes empezar a colocar en orden alfabético

2024-11-20 17:21 UTC, semanticmx commented on cap-09/src/index.html
> +<!DOCTYPE html>
muy bien!

2024-11-20 18:28 UTC, semanticmx approved these changes
gracias!

2024-11-25 16:00 UTC, Carmen-Mercado approved these changes
Gracias!

2024-11-25 20:21 UTC, merged