Capitulo 11 curso de HTML5
Juan-Alejandro-Arriaga/html5 pull request #19
Opened 2024-12-02 20:37 UTC by Juan-Alejandro-Arriaga

# what
* Capitulo 11 del curso de HTML5
# why
* Continuación de cursos
# references
* https://diveinto.html5doctor.com/history.html

2024-12-02 23:58 UTC, semanticmx requested changes
muy bien!

2024-12-02 23:58 UTC, semanticmx commented on cap-11/README.md
> +Tengo 2 paginas y se requiere nacegar en paginas "A" y
nacegar

2024-12-02 23:58 UTC, semanticmx commented on cap-11/README.md
> +            id="photoimg"
muy bien, podemos ponerle la cereza en el pastel listando los atributos en orden alfabético?

Por ejemplo, ahora tienes:

```html
            id="photoimg" 
             src="gallery/1972-fer-500.jpg"
            alt="Fer" 
            width="500" 
            height="375"
```

que quede como:

```html
            alt="Fer" 
            height="375"
            id="photoimg" 
            src="gallery/1972-fer-500.jpg"
            width="500" 
```

2024-12-03 00:05 UTC, semanticmx commented on cap-11/src/index.html
> +                padding: 10px 20px;
gracias!

2024-12-03 00:05 UTC, semanticmx approved these changes
muy bien!

2024-12-03 00:06 UTC, Juan-Alejandro-Arriaga commented on cap-11/src/index.html
> +                padding: 10px 20px;
👍

2024-12-03 18:21 UTC, Carmen-Mercado approved these changes
Muy bien, gracias!

2024-12-03 18:23 UTC, merged