Features/0 resumen cap
Juan-Alejandro-Arriaga/html5 pull request #3
Opened 2024-09-23 22:03 UTC by Gokualexpro

# what
* Se realizo resumen del capitulo 0

# why
* Para continuar con el curso de HTML5

# references
![Captura de pantalla 2024-09-23 154858](https://github.com/user-attachments/assets/a64277e0-d1c9-446e-9ccd-89dfc60faeeb)

2024-09-25 15:17 UTC, semanticmx requested changes
Solo es cuestión de mover el README:md y queda.

2024-09-25 15:17 UTC, semanticmx commented on PORTAFOLIO SEMANTIC GITHUB/cap-00/README.md
> +# Introducción | Resumen 5 cosas a saber sobre HTML5
El folder `PORTAFOLIO SEMANTIC...` lo puedes quitar, porque este repositorio solo te va a servir para HTML5, los demás proyectos que hagas estarán en otros repos.

Luego el README.md ya puede quedar en el directorio raíz.

2024-09-25 15:17 UTC, semanticmx commented on PORTAFOLIO SEMANTIC GITHUB/cap-00/README.md
> +### 2. Tu no necesitas tirar nada:
Más que una traducción el resumen debe ser sobre lo que entendiste, para los siguientes capítulos trata de explicar lo que comprendiste del capítulo.

2024-09-25 18:09 UTC, semanticmx approved these changes
gracias!

En otro PR por favor agrega un README.md al directorio raíz, este es necesario para mostrar info general del repositorio al navegar en GitHub

2024-09-30 19:11 UTC, Carmen-Mercado approved these changes

2024-09-30 19:11 UTC, Carmen-Mercado commented on PORTAFOLIO SEMANTIC GITHUB/cap-00/README.md
El resumen lo veo bien.
Para los PR vamos a agregar una plantilla a la carpeta .git con un archivo llamado **pull_request_template.md** con el siguiente texto.

## what

- Describe high-level what changed as a result of these commits (i.e. added PR template)
- Be concise and to the point

## why

- Provide the justifications for the changes (e.g. avoid shadow imports)
- Describe why these changes were made (e.g. mixpanel package shadows mixpanel module when packages are created under
  project root.)
- Be concise and to the point

## references

- Link to any supporting GitHub issues or helpful documentation to add some context (e.g. stackoverflow)
- Or external urls (
  e.g https://github.com/cloudposse/terraform-aws-elasticache-redis/blob/master/.github/PULL_REQUEST_TEMPLATE.md)

Está plantilla nos permitira que cada que envies un PR te aparezcan dichas preguntas y nos ayuda a darnos una idea de que se realizo en dicho PR

2024-09-30 19:11 UTC, Carmen-Mercado commented on Proyectomiale/abreme.txt
Solo como comentario, trata de que todos los ejemplos que agregues sean  relacionados con los temas que abordan los capítulos y revisa los commits que realizas.

2024-09-30 19:11 UTC, Carmen-Mercado commented on Proyectomiale/INDEX.html
Acá igual solo como comentario, recuerda que el nombre correcto es index.htm, en minúsculas.

2024-09-30 20:46 UTC, merged