Features/1 resume cap
Juan-Alejandro-Arriaga/html5 pull request #5
Opened 2024-09-25 22:26 UTC by Juan-Alejandro-Arriaga

2024-09-26 02:07 UTC, semanticmx commented
@Juan-Alejandro-Arriaga configura por favor la protección de branches para que no se puedan hacer commits a main directamente y que no se pueda mezclar el PR si no se ha aprobado previamente

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule

2024-09-26 02:10 UTC, semanticmx requested changes

2024-09-26 02:10 UTC, semanticmx commented on cap-01/README.md
> +< img > se le coloca de preferencia al final "imagen/jpeg" para indicar que es un formato de imagen de tipo Jpeg, además explica que tu al ingresar a una página web esta envía el "header" a tu navega
muy bien,

solo que las etiquetas HTML no llevan espacion al inicio en lugar de `< img >` debes escribir `<img>` or `<img />`.

Entonces por favor hay que actualizar todas las menciones a etiquetas HTML para quitar esos espacios.

Puedes utilizar el backtick ("`")  para formatear el código.

2024-09-30 19:09 UTC, semanticmx approved these changes
gracias!

2024-09-30 19:10 UTC, Carmen-Mercado approved these changes

2024-10-07 15:33 UTC, Carmen-Mercado requested changes

2024-10-07 15:33 UTC, Carmen-Mercado commented on cap-01/README.md
> +Además de el atributo "name" *Tony* introdujo el atributo "HREF" donde al principio se podía referenciar (referenece en inglés, de ahí REF de HREF), de ahí también la incluye en la etiqueta `<A>`
Recuerda que el  las etiquetas van en minúsculas

2024-10-07 15:33 UTC, Carmen-Mercado commented on ejer5.psc
El resumen del capítulo esta bien, solo que vamos a revisar como se están realizando los PR ya que solo se tendrían que mostrar los archivos modificados o añadidos, y en el PR anterior y en este vuelven a aparecer.
Una vez que se haya mezclado el PR 1 en main vamos a mezclar main en  tu branch  del capitulo 1 para que solo aparezca el archivo README

2024-10-07 16:15 UTC, closed without merging