Features/2 resume cap
Juan-Alejandro-Arriaga/html5 pull request #8
Opened 2024-10-02 23:14 UTC by Juan-Alejandro-Arriaga

# what
* Resumen capitulo 2 del libro HTML5
# why
* Continuación con mi capacitación 
# references
* https://diveinto.html5doctor.com/detect.html

2024-10-03 14:52 UTC, semanticmx requested changes
muy bien, solo unos pequeños ajustes

2024-10-03 14:52 UTC, semanticmx commented on cap-02/README.md
> +### Trabajadores de la web
Hay algunas palabras que se pueden utilizar en inglés que ya son comunes cuando hablamos en expañol, como los Workers de javascript, entonces en algunos casos como este, los podemos dejar con su palabra en inglés.

2024-10-03 14:52 UTC, semanticmx commented on cap-02/README.md
> + Estos permiten que en el fondo permita correr diferentes "*threads*" al mismo tiempo
Como en este caso _threads_ está bien utilizado aquí. Solo que formalmente, hay que usar itálicas cuando escribimos este tipo de palabras.

2024-10-04 22:54 UTC, Carmen-Mercado requested changes

2024-10-04 22:54 UTC, Carmen-Mercado commented on cap-02/README.md
> +Dentro de Html5 existe el **DOM**, que son todos los elementos que haya dentro del documento ya sean `<p> <a> <div>`
En esta línea estás hablando en plural, no en singular.

2024-10-04 22:54 UTC, Carmen-Mercado commented on cap-02/README.md
> +1. Comprobar si existe esa propiedad en un objeto global
Ayúdame a corregir los índices de la lista.

2024-10-04 22:54 UTC, Carmen-Mercado commented on cap-02/README.md
> +No hay necesidad de llamarlo , corre automáticamente, funciona de tal manera que, si al tu meter un Canva dentro de tu navegador este lo soportara , su propiedad *"Modernizr. canvas"* será ***true***
Ayúdame a revisar ortografía y redacción de esta línea.

2024-10-04 22:54 UTC, Carmen-Mercado commented on cap-02/README.md
> +Debido a que existen distintos formatos de video , el navegador debe entender
Acá no termino de entender la idea.

2024-10-04 22:54 UTC, Carmen-Mercado commented on cap-02/README.md
> +Es la manera con la que sabes en que parte del mundo estas y para saberlo esta la dirección IP o el "***GPS***" que calcula la latitud y altitud
Ayúdame a corroborar, me parece que es "latitud y longitud" no altitud.

2024-10-06 21:14 UTC, semanticmx commented on cap-02/README.md
> +**.canPlayType()** la cual regresa un valor tipo cadena dependiendo si puede o no reproducir el vídeo
`video` no lleva acento

2024-10-06 21:15 UTC, semanticmx approved these changes
muy bien, los ajustes pendientes los podemos agregar junto con el siguiente PR

2024-10-07 15:30 UTC, Carmen-Mercado approved these changes
Muy bien, gracias!

2024-10-07 15:39 UTC, merged